[package]
name = "graphite-desktop-embedded-resources"
description = "Graphite Desktop Embedded Resources"
authors = ["Graphite Authors <contact@graphite.art>"]
license = "Apache-2.0"
repository = "https://github.com/nil-is-lin/Graphite.git"
edition = "2024"
rust-version = "1.87"

[dependencies]
include_dir = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(embedded_resources)'] }
